# Generated by Django 3.1 on 2020-08-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200820_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\shubh\\PycharmProjects\\mysiteS20\\media'),
        ),
    ]
